### ISSUE TITLE
Hello! Update dev dep - node-css-mqpacker 

### ISSUE THREAD

**Issue by ghost** [shoonia/css-mqpacker-webpack-plugin#1]
Hey! Could you please update dev dep - node-css-mqpacker  because with new webpack 5 it writes a warning:
(node:7231) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by shoonia** [comment]
The deprecation warning is sending from last-call-webpack-plugin

I hope a PR with fix will be merged https://github.com/NMFR/last-call-webpack-plugin/pull/9

**Comment by shoonia** [comment]
Fixed

```bash
npm i css-mqpacker-webpack-plugin@0.10.0 -D
```
